# Generated by Django 5.1.1 on 2025-07-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveloption',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
